@startuml NFT-v2
header NFT-v2
title NFT-v2-transferOwnership
skinparam maxMessageSize 200
skinparam guillemet true
autonumber
actor "Owner" as O
participant "Data" as D << Data >>
participant "IO" as IO << IndexOwner >>
participant "IOR" as IOR << IndexOwnerRoot >>
O -> D ++: transferOwnership(addrTo)
    D -> IO : destroy
    D -> IOR : destroy
    D -> D  :changeOwner
    D -> IO : deploy
    D -> IOR : deploy
@enduml