@startuml TrueNft
header TrueNft
title TrueNft transfer
skinparam maxMessageSize 200
skinparam guillemet true
autonumber
actor "Owner" as O
participant "NftRoot" as R << NftRoot >>
participant "Nft" as N << Nft >>
participant "NftData" as D << NftData >>
O -> R ++: transferOwnership
    R -> R : check smcNft and ownership
    R -> R : add new owner to _pendingOwners
    R -> N ++: destruct
    return recieve()
    R -> R : fetch new owner
    R -> D ++: setOwner
    return success
    R -> R : delete new owner from _pendingOwners
    R -> N ++: deploy new smcNft
    return success
return success
@enduml